### ISSUE TITLE
Both web and MacOS versions are severely broken

### ISSUE THREAD

**Issue by popdynamite5511** [hdfsyu/The-Mysterious-Prison#1]
The MacOS compiled version thinks it's for the PowerPC architecture, and the web version flickers and the textures look corrupted and uncentered

**Comment by hdfsyu** [comment]
@popdynamite5511 Web version is completely fine, and the macOS version is compiled using neko, so you can't run it on macOS for now (the web version is probably flickering because of your browser, use safari or opera)

**Comment by hdfsyu** [comment]
So you have to pull request or something to fix it, closing issue

**Comment by popdynamite5511** [comment]
can you remove the macos version until it is fixed then since it's basically useless

**Comment by hdfsyu** [comment]
"mac-windows-linux"
if i remove one, i effectively remove all

**Comment by popdynamite5511** [comment]
then don't put them all in the same folder and upload them, just upload the exes and and stuff as separate downloads
